name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  provider: ^6.1.1
  http: ^0.13.5
  shared_preferences: ^2.1.0
  photo_view: ^0.14.0
  dio: ^5.4.1
  image_picker: ^1.0.7
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.4+3
  google_maps_flutter: ^2.2.5
  flutter_google_places: ^0.3.0
  geocoding: ^2.1.0
  geolocator: ^11.0.0
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.1.10
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^16.3.2
  path_provider: ^2.0.14
  connectivity: ^3.0.6
  carousel_slider: ^4.2.1
  fluro: ^2.0.5
  url_strategy: ^0.2.0
  universal_html: ^2.2.1
  flutter_widget_from_html_core: ^0.14.11
  phone_number: ^2.1.0
  country_code_picker: 3.0.0
  flutter_typeahead: ^4.3.7
  flutter_inappwebview: ^5.7.2+3
  cached_network_image: ^3.2.3
  audioplayers: ^5.2.1
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  expandable_bottom_sheet: 1.1.1+1
  dotted_border: ^2.0.0+3
  share_plus: ^7.2.2
  scroll_to_index: ^3.0.1
  simple_speed_dial: ^0.1.7
  flutter_lints: ^3.0.1
  sign_in_with_apple: ^5.0.0
  firebase_auth: ^4.17.5
  flutter_svg: ^2.0.9
  flutter_xlider: ^3.5.0
  firebase_crashlytics: ^3.4.8



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700